version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Jingyi090/ollama"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"